# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'YPOCDevTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YPOCDevTools
  pod 'AFNetworking', '~> 4.0.1'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'RealReachability'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'Toast'
  

  target 'YPOCDevToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YPOCDevToolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
