# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'YPOCDevTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YPOCDevTools
  pod 'AFNetworking', '~> 3.2.1'
  pod 'IQKeyboardManager'
  pod 'MJRefresh', '~> 3.1.15.7'  
  pod 'Masonry', '~> 1.1.0'
  pod 'RealReachability', '~> 1.3.0'
  pod 'SDWebImage', '~> 4.4.2'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Toast', '~> 4.0.0'
  

  target 'YPOCDevToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YPOCDevToolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
